### ISSUE TITLE
Getting started (Dev) is not valid.

### ISSUE THREAD

**Issue by evadogstar** [MyHush/hushjs#2]
Getting started (Dev) manual is not valid. `yarn` (installeted from cmdtest) say that there are no `install` and `build`

git clone https://github.com/MyHush/hushjs.git
cd hushjs
yarn install
yarn build

# Dev flow
flow status
yarn build
yarn test

**Comment by joshgentry** [comment]
Sorry this wasn't responded to earlier. The `cmdtest` package installed on Ubuntu is not the appropriate way to install `yarn`.

Please see this URL for information on `yarn` installation on Debian / Ubuntu:
https://yarnpkg.com/lang/en/docs/install/#debian-stable
